name = "DisjunctiveConstraints"
uuid = "ca2457d0-b00c-11e9-1bb0-270bb01e5b2e"
authors = ["Joey Huchette <joehuchette@gmail.com>"]
version = "0.1.0"

[deps]
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"

[extras]
Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Cbc", "Test"]
